import { AssetSchema, SlugSchema, StellarPublicKeySchema } from '@payorder/shared';
import {
  ORDER_STATUSES,
  PaymentOrder,
  normalizeOrderSource,
  type OrderStatus,
  type PaymentOrderEvent,
} from '../../../domain/payment-order/index.js';
import type {
  NewPaymentOrderEventRow,
  NewPaymentOrderRow,
  PaymentOrderRow,
} from '../schema/payment-orders.js';

function parseStatus(value: string): OrderStatus {
  if (!(ORDER_STATUSES as readonly string[]).includes(value)) {
    throw new Error(`Unknown order status in DB: ${value}`);
  }
  return value as OrderStatus;
}

/**
 * Maps the `PaymentOrder` aggregate to/from its `payment_orders` row (spec 09 §2). Numeric
 * `amount` and `due_date` are kept as strings end-to-end to preserve precision and
 * determinism (no floats).
 */
export function paymentOrderToRow(order: PaymentOrder): NewPaymentOrderRow {
  return {
    id: order.id,
    tenantId: order.tenantId,
    externalId: order.externalId,
    amount: order.amount,
    assetCode: order.asset.code,
    assetIssuer: order.asset.issuer,
    receiverWalletPublicKey: order.receiverWallet,
    canonicalPayloadHash: order.canonicalPayloadHash,
    status: order.status,
    source: order.source,
    dueDate: order.dueDate,
    description: order.description,
    publicPaymentSlug: order.publicSlug,
    sorobanContractId: order.sorobanContractId,
    blockchainTransactionHash: order.blockchainTxHash,
    metadata: order.metadata,
    correlationId: order.correlationId,
    createdAt: order.createdAt,
    updatedAt: order.updatedAt,
    paidAt: order.paidAt,
  };
}

export function paymentOrderFromRow(row: PaymentOrderRow): PaymentOrder {
  return PaymentOrder.fromPersistence({
    id: row.id,
    tenantId: row.tenantId,
    externalId: row.externalId,
    amount: row.amount,
    asset: AssetSchema.parse({ code: row.assetCode, issuer: row.assetIssuer }),
    receiverWallet: StellarPublicKeySchema.parse(row.receiverWalletPublicKey),
    canonicalPayloadHash: row.canonicalPayloadHash,
    status: parseStatus(row.status),
    source: normalizeOrderSource(row.source),
    dueDate: row.dueDate,
    description: row.description,
    publicSlug: SlugSchema.parse(row.publicPaymentSlug),
    sorobanContractId: row.sorobanContractId,
    blockchainTxHash: row.blockchainTransactionHash,
    metadata: (row.metadata ?? {}) as Record<string, unknown>,
    correlationId: row.correlationId,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    paidAt: row.paidAt,
  });
}

/**
 * Map a pulled domain event onto an insertable `payment_order_events` row (spec 09 §3).
 * The row id is generated by the database (`gen_random_uuid()`).
 */
export function paymentOrderEventToRow(
  orderId: string,
  event: PaymentOrderEvent,
  correlationId: string | null,
): NewPaymentOrderEventRow {
  return {
    paymentOrderId: orderId,
    eventType: event.type,
    payload: event.payload,
    correlationId,
    createdAt: event.occurredAt,
  };
}
